"""
Build and cache a PixelMap-focused probe features dictionary from
Bill Karsh's Neuropixels_probe_features JSON.

The cache (pixelmap_probe_features.json) is rebuilt from the source JSON
every time this module is imported, so it stays current when the source
is updated without any manual step.

Exposed module-level names
--------------------------
PROBE_FEATURES : dict[str, dict]
    Keyed by IMEC part number (e.g. "NP2003").  Each value has:
      SpikeGLX_probe_number  – legacy integer type used in old IMRO headers
      IMRO_format            – e.g. "imro_np2003"
      n_readouts_total       – total simultaneous readout channels (num_readout_channels)
      n_readouts_per_shank   – per-shank readout limit (channels_per_bank)
      n_sites_total          – total physical electrodes (total_electrodes)
      n_sites_per_shank      – electrodes per shank (electrodes_per_shank)
      probe_name             – human-readable description
      horizontal_pitch       – electrode horizontal pitch (µm)
      vertical_pitch         – electrode vertical pitch (µm)
      layout_geometry        – "staggered", "linear", etc.
      num_shanks             – number of shanks
      pixelmap_probe_type    – PixelMap internal type ("1.0", "2.0-1shank",
                               "2.0-4shanks") or None if not yet supported.

PROBE_TYPE_MAP : dict[str, list[str]]
    Maps each pixelmap_probe_type to the sorted list of part numbers that
    belong to it.  Only entries with pixelmap_probe_type != None appear.

IMRO_FORMAT_TO_PROBE_TYPE : dict[str, str]
    Maps each IMRO format string to a pixelmap_probe_type (or None).

LEGACY_PROBE_TYPE_MAP : dict[str, list[int]]
    The original integer-based mapping kept for parsing old IMRO files.

LEGACY_INT_TO_IMRO_FORMAT : dict[int, str]
    Maps each known legacy integer probe type to its IMRO format string.
"""

import json
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_WIRING_MAPS_DIR = Path(__file__).resolve().parent.parent / "wiring_maps"
_SOURCE_JSON = _WIRING_MAPS_DIR / "Neuropixels_probe_features_Bill_Karsh.json"
_CACHE_JSON  = _WIRING_MAPS_DIR / "pixelmap_probe_features.json"

# ---------------------------------------------------------------------------
# Static mappings
# ---------------------------------------------------------------------------

# IMRO format string → pixelmap probe type (wiring-file family).
# Formats not listed here are not yet supported by PixelMap.
IMRO_FORMAT_TO_PROBE_TYPE: dict[str, str | None] = {
    "imro_np1000":  "1.0",
    "imro_np2000":  "2.0-1shank",
    "imro_np2003":  "2.0-1shank",
    "imro_np2010":  "2.0-4shanks",
    "imro_np2013":  "2.0-4shanks",
    "imro_np2020":  "2.0-4shanks",
}

# Legacy integer probe type numbers for parsing IMRO files generated by
# SpikeGLX < 20260115.  Preserved exactly as the old PROBE_TYPE_MAP.
LEGACY_PROBE_TYPE_MAP: dict[str, list[int]] = {
    "1.0":          [0, 1020, 1030, 1100, 1120, 1121, 1122, 1123, 1200, 1300],
    "2.0-1shank":   [21, 2003, 2004],
    "2.0-4shanks":  [24, 2013, 2014],
}

# Legacy integer → IMRO format string (for parsing old IMRO headers)
LEGACY_INT_TO_IMRO_FORMAT: dict[int, str] = {
    **{n: "imro_np1000" for n in LEGACY_PROBE_TYPE_MAP["1.0"]},
    21: "imro_np2000",
    2003: "imro_np2003", 2004: "imro_np2003",
    24: "imro_np2010",
    2013: "imro_np2013", 2014: "imro_np2013",
    2020: "imro_np2020", 2021: "imro_np2020",
}

# Part numbers for which int(part_number[2:]) does NOT equal the legacy
# SpikeGLX integer type.
_SPIKEGLIX_NUMBER_EXCEPTIONS: dict[str, int] = {
    # Standard NP 1.0 and its short-NHP variants all report as type 0.
    "NP1000": 0, "NP1001": 0,
    "NP1010": 0, "NP1011": 0, "NP1012": 0, "NP1013": 0,
    "NP1014": 0, "NP1015": 0, "NP1016": 0, "NP1017": 0,
    # Phase-1 pilot probes (NP-prefix)
    "NP2000": 21,   # NP 2.0 single-shank Phase 1 → type 21
    "NP2010": 24,   # NP 2.0 four-shank  Phase 1 → type 24
    # Old PRB-prefix pilot part numbers
    "PRB_1_2_0480_2": 0,    # NP 1.0 pilot
    "PRB_1_4_0480_1": 0,    # NP 1.0 pilot
    "PRB_1_4_0480_1_C": 0,  # NP 1.0 pilot with cap
    "PRB2_1_2_0640_0": 21,  # NP 2.0 single-shank Phase 1 pilot
    "PRB2_4_2_0640_0": 24,  # NP 2.0 four-shank  Phase 1 pilot
}


def _spikeglix_probe_number(part_number: str) -> int:
    """Return the legacy SpikeGLX integer type for a given part number."""
    if part_number in _SPIKEGLIX_NUMBER_EXCEPTIONS:
        return _SPIKEGLIX_NUMBER_EXCEPTIONS[part_number]
    try:
        return int(part_number[2:])
    except ValueError:
        return 0  # Unknown format; treat as generic NP 1.0


# ---------------------------------------------------------------------------
# Build / cache
# ---------------------------------------------------------------------------

def _build(source_json_path: Path) -> dict:
    """Read Bill Karsh's JSON and return the PixelMap-focused dict."""
    with open(source_json_path) as f:
        raw = json.load(f)

    # The JSON may have a single top-level "neuropixels_probes" key.
    probes_raw = raw.get("neuropixels_probes", raw)

    result: dict = {}
    for pn, data in probes_raw.items():
        imro_fmt = data["imro_table_format_type"]
        n_shanks = int(data["num_shanks"])

        ptype = IMRO_FORMAT_TO_PROBE_TYPE.get(imro_fmt)
        # 4-shank type only applies to probes that actually have 4 shanks.
        if ptype == "2.0-4shanks" and n_shanks != 4:
            ptype = None

        result[pn] = {
            "SpikeGLX_probe_number": _spikeglix_probe_number(pn),
            "IMRO_format":           imro_fmt,
            "n_readouts_total":      int(data["num_readout_channels"]),
            "n_readouts_per_shank":  int(data["channels_per_bank"]),
            "n_sites_total":         int(data["total_electrodes"]),
            "n_sites_per_shank":     int(data["electrodes_per_shank"]),
            "probe_name":            data["description"],
            "horizontal_pitch":      float(data["electrode_pitch_horz_um"]),
            "vertical_pitch":        float(data["electrode_pitch_vert_um"]),
            "layout_geometry":       data["electrode_layout_type"],
            "num_shanks":            n_shanks,
            "pixelmap_probe_type":   ptype,
        }
    return result


# ---------------------------------------------------------------------------
# Module-level initialisation
# ---------------------------------------------------------------------------

PROBE_FEATURES: dict = _build(_SOURCE_JSON)

# Write/refresh the cache
_CACHE_JSON.parent.mkdir(parents=True, exist_ok=True)
with open(_CACHE_JSON, "w") as _f:
    json.dump(PROBE_FEATURES, _f, indent=2)

# Build PROBE_TYPE_MAP: probe_type → sorted list of part numbers.
# Order preserves the historical probe-type ordering.
_PROBE_TYPE_ORDER = ["1.0", "2.0-1shank", "2.0-4shanks"]
PROBE_TYPE_MAP: dict[str, list[str]] = {pt: [] for pt in _PROBE_TYPE_ORDER}
for _pn, _feat in PROBE_FEATURES.items():
    _pt = _feat["pixelmap_probe_type"]
    if _pt in PROBE_TYPE_MAP:
        PROBE_TYPE_MAP[_pt].append(_pn)
for _pt in PROBE_TYPE_MAP:
    PROBE_TYPE_MAP[_pt].sort()
