"""
Build and cache a PixelMap-focused probe features dictionary from
Bill Karsh's Neuropixels_probe_features JSON.

The cache (pixelmap_probe_features.json) is rebuilt from the source JSON
every time this module is imported, so it stays current when the source
is updated without any manual step.

Exposed module-level names
--------------------------
PROBE_FEATURES : dict[str, dict]
    Keyed by IMEC part number (e.g. "NP2003").  Each value has:
      SpikeGLX_probe_number  – legacy integer type used in old IMRO headers
      IMRO_format            – e.g. "imro_np2003"
      n_readouts_total       – total simultaneous readout channels (num_readout_channels)
      n_readouts_per_shank   – per-shank readout limit (channels_per_bank)
      n_sites_total          – total physical electrodes (total_electrodes)
      n_sites_per_shank      – electrodes per shank (electrodes_per_shank)
      probe_name             – human-readable description
      horizontal_pitch       – electrode horizontal pitch (µm)
      vertical_pitch         – electrode vertical pitch (µm)
      layout_geometry        – "staggered", "linear", etc.
      num_shanks             – number of shanks
      pixelmap_probe_type    – PixelMap internal type string, or None if unknown.

PROBE_TYPE_MAP : dict[str, list[str]]
    Maps each pixelmap_probe_type to the sorted list of part numbers that
    belong to it.

IMRO_FORMAT_TO_PROBE_TYPE : dict[str, str | None]
    Maps each known IMRO format string to a pixelmap_probe_type, or None
    when the format alone is ambiguous (imro_np1000 is shared by many families).

LEGACY_PROBE_TYPE_MAP : dict[str, list[int]]
    Maps each probe type to its known legacy SpikeGLX integer probe numbers,
    for parsing IMRO files generated by SpikeGLX < 20260115.

LEGACY_INT_TO_IMRO_FORMAT : dict[int, str]
    Maps each known legacy integer probe type to its IMRO format string.
"""

import json
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_WIRING_MAPS_DIR = Path(__file__).resolve().parent.parent / "wiring_maps"
_SOURCE_JSON = _WIRING_MAPS_DIR / "Neuropixels_probe_features_Bill_Karsh.json"
_CACHE_JSON  = _WIRING_MAPS_DIR / "pixelmap_probe_features.json"

# ---------------------------------------------------------------------------
# Probe type taxonomy
# ---------------------------------------------------------------------------
# Each type is hardware-homogeneous: same geometry, site count, and readout
# count.  Types marked NOT YET SUPPORTED have no wiring map yet; they appear
# in PROBE_FEATURES and PROBE_TYPE_MAP but the GUI will not allow selection.
#
# Currently SUPPORTED: "1.0", "2.0-1shank", "2.0-4shanks"
#
# Type               geometry / sites / readout
# -----------------------------------------------------------------
# 1.0                960 sites, staggered 32×20 µm, 384 ro
# NHP-short-linear   960 sites, linear   32×20 µm, 384 ro
# NHP-medium-staggered 2496 sites, staggered 87×20 µm, 384 ro
# NHP-medium-linear  2496 sites, linear  103×20 µm, 384 ro
# NHP-long-staggered 4416 sites, staggered 87×20 µm, 384 ro
# NHP-long-linear    4416 sites, linear  103×20 µm, 384 ro
# NHP-passive         128 sites, staggered 32×31 µm, 128 ro
# UHD1                384 sites, 8×48 layout, 6×6 µm, 384 ro
# UHD2               6144 sites, 8×768 layout, 6×6 µm, 384 ro  (imro_np1110)
# UHD3-2x192          384 sites, 2×192 layout, 4.5×4.5 µm, 384 ro
# UHD3-1x384          384 sites, 1×384 layout, 0×3 µm, 384 ro
# UHD3-16x24          384 sites, 16×24 layout, 3×3 µm, 384 ro
# UHD3-12x32          384 sites, 12×32 layout, 4.5×4.5 µm, 384 ro
# Opto                960 sites, linear 48×20 µm, 384 ro
# 2.0-1shank         1280 sites, 32×15 µm, 1 shank, 384 ro
# 2.0-4shanks        1280 sites/shank, 32×15 µm, 4 shanks, 384 ro
# QuadBase           1280 sites/shank, 32×15 µm, 4 shanks, 1536 ro (384/shank)
# NXT-passive         128 sites, 1×128 layout, 0×15 µm, 128 ro
# NXT-1shank         1280 sites, 32×15 µm, 1 shank, 1536 ro (912/shank)
# NXT-4shank         1280 sites/shank, 32×15 µm, 4 shanks, 1536 ro (912/shank)

# Ordered list used to build PROBE_TYPE_MAP with stable ordering.
_PROBE_TYPE_ORDER: list[str] = [
    "1.0",
    "NHP-short-linear",
    "NHP-medium-staggered", "NHP-medium-linear",
    "NHP-long-staggered",   "NHP-long-linear",
    "NHP-passive",
    "UHD1", "UHD2",
    "UHD3-2x192", "UHD3-1x384", "UHD3-16x24", "UHD3-12x32",
    "Opto",
    "2.0-1shank",
    "2.0-4shanks",
    "QuadBase",
    "NXT-passive", "NXT-1shank", "NXT-4shank",
]

# Explicit part-number → pixelmap probe type mapping.
# NP1010-1014 (NHP short staggered) share identical geometry with standard
# 1.0 (960 sites, staggered 32×20 µm) and thus belong to the "1.0" type.
_PART_NUMBER_TO_PROBE_TYPE: dict[str, str] = {
    # ---- Standard 1.0 (and NHP short staggered: same geometry) ----
    "PRB_1_2_0480_2": "1.0",
    "PRB_1_4_0480_1": "1.0",
    "PRB_1_4_0480_1_C": "1.0",
    "NP1000": "1.0",
    "NP1001": "1.0",
    # ---- NHP staggered: same as 1.0 ----
    "NP1010": "1.0",
    "NP1011": "1.0",
    "NP1012": "1.0",
    "NP1013": "1.0",
    "NP1014": "1.0",
    # ---- NHP short linear (960 sites, linear 32×20 µm) ----
    "NP1015": "NHP-short-linear",
    "NP1016": "NHP-short-linear",
    "NP1017": "NHP-short-linear",
    # ---- NHP medium (2496 sites) ----
    "NP1020": "NHP-medium-staggered",
    "NP1021": "NHP-medium-staggered",
    "NP1022": "NHP-medium-linear",
    # ---- NHP long (4416 sites) ----
    "NP1030": "NHP-long-staggered",
    "NP1031": "NHP-long-staggered",
    "NP1032": "NHP-long-linear",
    "NP1033": "NHP-long-linear",
    "NP1040": "NHP-long-linear",
    "NP1041": "NHP-long-linear",
    "NP1042": "NHP-long-linear",
    "NP1050": "NHP-long-linear",
    "NP1051": "NHP-long-linear",
    # ---- NHP passive (128 sites, 128ch headstage) ----
    "NP1200": "NHP-passive",
    "NP1210": "NHP-passive",
    # ---- UHD ----
    "NP1100": "UHD1",
    "NP1110": "UHD2",
    "NP1120": "UHD3-2x192",
    "NP1121": "UHD3-1x384",
    "NP1122": "UHD3-16x24",
    "NP1123": "UHD3-12x32",
    # ---- Opto ----
    "NP1300": "Opto",
    # ---- 2.0 single-shank (1280 sites, 32×15 µm) ----
    # NP2006 is staggered but uses the same wiring structure as the linear variant.
    "NP2000": "2.0-1shank",
    "PRB2_1_2_0640_0": "2.0-1shank",
    "NP2003": "2.0-1shank",
    "NP2004": "2.0-1shank",
    "NP2005": "2.0-1shank",
    "NP2006": "2.0-1shank",
    # ---- 2.0 four-shank (1280 sites/shank, 32×15 µm) ----
    "NP2010": "2.0-4shanks",
    "PRB2_4_2_0640_0": "2.0-4shanks",
    "NP2013": "2.0-4shanks",
    "NP2014": "2.0-4shanks",
    # ---- QuadBase (4 shanks, 384 ro/shank, 1536 ro total) ----
    "NP2020": "QuadBase",
    "NP2021": "QuadBase",
    # ---- NXT ----
    "NP3000": "NXT-passive",
    "NP3010": "NXT-1shank",
    "NP3011": "NXT-1shank",
    "NP3020": "NXT-4shank",
    "NP3021": "NXT-4shank",
    "NP3022": "NXT-4shank",
    "NP3023": "NXT-4shank",
    "NP3024": "NXT-4shank",
}

# ---------------------------------------------------------------------------
# IMRO format → probe type
# imro_np1000 is ambiguous (used by 1.0, NHP-*, UHD-*, Opto, NXT-passive)
# so it maps to None; per-probe classification uses _PART_NUMBER_TO_PROBE_TYPE.
# ---------------------------------------------------------------------------
IMRO_FORMAT_TO_PROBE_TYPE: dict[str, str | None] = {
    "imro_np1000":  None,           # ambiguous; see _PART_NUMBER_TO_PROBE_TYPE
    "imro_np1110":  "UHD2",
    "imro_np2000":  "2.0-1shank",
    "imro_np2003":  "2.0-1shank",
    "imro_np2010":  "2.0-4shanks",
    "imro_np2013":  "2.0-4shanks",
    "imro_np2020":  "QuadBase",
    "imro_np3010":  "NXT-1shank",
    "imro_np3020":  "NXT-4shank",
}

# ---------------------------------------------------------------------------
# Legacy integer probe type numbers (SpikeGLX < 20260115)
# Maps probe type → list of SpikeGLX integer IDs that belong to it.
# Used for parsing old IMRO file headers.
#
# Notes on integer 0:
#   NP1000, NP1001, NP1010-1014 all report as type 0 (same ASIC as std 1.0).
#   NP1015-1017 (NHP short linear) also report as 0 in old SpikeGLX — they
#   cannot be distinguished from 1.0 in legacy IMRO files.  Integer 0 is
#   therefore listed only under "1.0"; legacy parsing resolves 0 → "1.0".
# ---------------------------------------------------------------------------
LEGACY_PROBE_TYPE_MAP: dict[str, list[int]] = {
    "1.0":                   [0],
    "NHP-short-linear":      [0],            # SpikeGLX type 0 — indistinguishable from 1.0
    "NHP-medium-staggered":  [1020, 1021],
    "NHP-medium-linear":     [1022],
    "NHP-long-staggered":    [1030, 1031],
    "NHP-long-linear":       [1032, 1033, 1040, 1041, 1042, 1050, 1051],
    "NHP-passive":           [1200, 1210],
    "UHD1":                  [1100],
    "UHD2":                  [1110],
    "UHD3-2x192":            [1120],
    "UHD3-1x384":            [1121],
    "UHD3-16x24":            [1122],
    "UHD3-12x32":            [1123],
    "Opto":                  [1300],
    "2.0-1shank":            [21, 2003, 2004, 2005, 2006],
    "2.0-4shanks":           [24, 2013, 2014],
    "QuadBase":              [2020, 2021],
    "NXT-passive":           [3000],
    "NXT-1shank":            [3010, 3011],
    "NXT-4shank":            [3020, 3021, 3022, 3023, 3024],
}

# Legacy integer → IMRO format string (for parsing old IMRO file headers).
# Built from LEGACY_PROBE_TYPE_MAP + IMRO_FORMAT_TO_PROBE_TYPE, with
# manual overrides where the format differs from the type's primary format.
LEGACY_INT_TO_IMRO_FORMAT: dict[int, str] = {
    # imro_np1000 family
    0:    "imro_np1000",  # 1.0, NHP short (staggered and linear)
    1020: "imro_np1000",
    1021: "imro_np1000",  # NHP medium staggered
    1022: "imro_np1000",                        # NHP medium linear
    1030: "imro_np1000",
    1031: "imro_np1000",  # NHP long staggered
    1032: "imro_np1000",
    1033: "imro_np1000",  # NHP long linear
    1040: "imro_np1000",
    1041: "imro_np1000",
    1042: "imro_np1000",
    1050: "imro_np1000",
    1051: "imro_np1000",
    1100: "imro_np1000",  # UHD1
    1120: "imro_np1000",
    1121: "imro_np1000",  # UHD3
    1122: "imro_np1000",
    1123: "imro_np1000",
    1200: "imro_np1000",
    1210: "imro_np1000",  # NHP passive
    1300: "imro_np1000",  # Opto
    3000: "imro_np1000",  # NXT passive
    # imro_np1110 (UHD2 active)
    1110: "imro_np1110",
    # imro_np2000 (2.0 single-shank Phase 1 pilot)
    21:   "imro_np2000",
    # imro_np2003 (2.0 single-shank Phase 2)
    2003: "imro_np2003",
    2004: "imro_np2003",
    2005: "imro_np2003",
    2006: "imro_np2003",
    # imro_np2010 (2.0 four-shank Phase 1 pilot)
    24:   "imro_np2010",
    # imro_np2013 (2.0 four-shank Phase 2)
    2013: "imro_np2013",
    2014: "imro_np2013",
    # imro_np2020 (QuadBase)
    2020: "imro_np2020",
    2021: "imro_np2020",
    # imro_np3010 (NXT single-shank)
    3010: "imro_np3010",
    3011: "imro_np3010",
    # imro_np3020 (NXT four-shank)
    3020: "imro_np3020",
    3021: "imro_np3020",
    3022: "imro_np3020",
    3023: "imro_np3020",
    3024: "imro_np3020",
}

# ---------------------------------------------------------------------------
# SpikeGLX integer exceptions
# Part numbers for which int(part_number[2:]) does NOT equal the legacy
# SpikeGLX integer type written in IMRO headers.
# ---------------------------------------------------------------------------
_SPIKEGLIX_NUMBER_EXCEPTIONS: dict[str, int] = {
    # Standard NP 1.0: all report as type 0.
    "NP1000": 0,
    "NP1001": 0,
    # NHP short staggered: same ASIC as 1.0 → type 0.
    "NP1010": 0,
    "NP1011": 0,
    "NP1012": 0,
    "NP1013": 0,
    "NP1014": 0,
    # NHP short linear: also report as type 0 in legacy SpikeGLX.
    "NP1015": 0,
    "NP1016": 0,
    "NP1017": 0,
    # Phase-1 pilot probes (NP-prefix)
    "NP2000": 21,   # 2.0 single-shank Phase 1 → type 21
    "NP2010": 24,   # 2.0 four-shank  Phase 1 → type 24
    # Old PRB-prefix pilot part numbers
    "PRB_1_2_0480_2":  0,
    "PRB_1_4_0480_1":  0,
    "PRB_1_4_0480_1_C": 0,
    "PRB2_1_2_0640_0": 21,
    "PRB2_4_2_0640_0": 24,
}


def _spikeglix_probe_number(part_number: str) -> int:
    """Return the legacy SpikeGLX integer type for a given part number."""
    if part_number in _SPIKEGLIX_NUMBER_EXCEPTIONS:
        return _SPIKEGLIX_NUMBER_EXCEPTIONS[part_number]
    try:
        return int(part_number[2:])
    except ValueError:
        return 0  # Unknown format; treat as generic NP 1.0


# ---------------------------------------------------------------------------
# Build / cache
# ---------------------------------------------------------------------------

def _build(source_json_path: Path) -> dict:
    """Read Bill Karsh's JSON and return the PixelMap-focused dict."""
    with open(source_json_path) as f:
        raw = json.load(f)

    probes_raw = raw.get("neuropixels_probes", raw)

    result: dict = {}
    for pn, data in probes_raw.items():
        imro_fmt = data["imro_table_format_type"]
        n_shanks = int(data["num_shanks"])

        ptype = _PART_NUMBER_TO_PROBE_TYPE.get(pn)

        result[pn] = {
            "SpikeGLX_probe_number": _spikeglix_probe_number(pn),
            "IMRO_format":           imro_fmt,
            "n_readouts_total":      int(data["num_readout_channels"]),
            "n_readouts_per_shank":  int(data["channels_per_bank"]),
            "n_sites_total":         int(data["total_electrodes"]),
            "n_sites_per_shank":     int(data["electrodes_per_shank"]),
            "probe_name":            data["description"],
            "horizontal_pitch":      float(data["electrode_pitch_horz_um"]),
            "vertical_pitch":        float(data["electrode_pitch_vert_um"]),
            "layout_geometry":       data["electrode_layout_type"],
            "num_shanks":            n_shanks,
            "pixelmap_probe_type":   ptype,
        }
    return result


# ---------------------------------------------------------------------------
# Module-level initialisation
# ---------------------------------------------------------------------------

PROBE_FEATURES: dict = _build(_SOURCE_JSON)

# Write/refresh the cache
_CACHE_JSON.parent.mkdir(parents=True, exist_ok=True)
with open(_CACHE_JSON, "w") as _f:
    json.dump(PROBE_FEATURES, _f, indent=2)

# Build PROBE_TYPE_MAP: probe_type → sorted list of part numbers.
PROBE_TYPE_MAP: dict[str, list[str]] = {pt: [] for pt in _PROBE_TYPE_ORDER}
for _pn, _feat in PROBE_FEATURES.items():
    _pt = _feat["pixelmap_probe_type"]
    if _pt in PROBE_TYPE_MAP:
        PROBE_TYPE_MAP[_pt].append(_pn)
for _pt in PROBE_TYPE_MAP:
    PROBE_TYPE_MAP[_pt].sort()
